version: "3"
networks:
  app-tier:
    driver: bridge
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_DATABASE=wordweaverdb
    networks:
      - app-tier
  web:
    build: .
    command: sh -c "python3 manage.py migrate --noinput && python3 manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "127.0.0.1:8001:8000"
    env_file:
      - .env
    depends_on:
      - mariadb
    restart: always
    networks:
      - app-tier
    volumes:
      - .:/app
