# Generated by Django 5.0.4 on 2024-04-07 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(error_messages={'null': 'blog title must be provided'}, help_text='blog title', max_length=100, verbose_name='title')),
                ('content', models.TextField(error_messages={'null': 'blog content must be provided'}, help_text='blog content', verbose_name='content')),
                ('creation_date', models.DateTimeField(auto_now_add=True, help_text='blog creation date', verbose_name='creation date')),
                ('last_update_date', models.DateTimeField(help_text='blog last update date', null=True, verbose_name='last update date')),
                ('user', models.ForeignKey(error_messages={'null': 'User must be provided'}, help_text='User who created this specific blog', on_delete=django.db.models.deletion.CASCADE, related_name='user_blog', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'ordering': ['-creation_date'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(error_messages={'null': 'Comment content must be provided'}, help_text='Comment content', verbose_name='Content')),
                ('creation_date', models.DateTimeField(auto_now_add=True, help_text='Comment creation date', verbose_name='Creation date')),
                ('author', models.ForeignKey(error_messages={'null': 'author must be provided'}, help_text='User who posted the comment', on_delete=django.db.models.deletion.CASCADE, related_name='author_comments', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('blog', models.ForeignKey(error_messages={'null': 'Blog must be provided'}, help_text='Blog to which the comment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='blog_comments', to='blog.blog', verbose_name='Blog')),
            ],
            options={
                'ordering': ['-creation_date'],
            },
        ),
    ]
