# Generated by Django 5.0.4 on 2024-04-14 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='last_update_date',
            field=models.DateTimeField(help_text='comment last update date', null=True, verbose_name='last update date'),
        ),
    ]
