#!/bin/bash

mariadb_ready() {
  python <<END
import sys
import mysql.connector
try:
    mydb = mysql.connector.connect(
        host="${DB_HOST}",
        user="${DB_USER}",
        password="${DB_PASS}",
        port="${DB_PORT}"
    )
except Exception as e:
    print(e)
    sys.exit(-1)
sys.exit(0)
END
}